tools:
    php_sim: true
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'spec/*'
                - 'test/*'
            paths: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'spec/*'
                - 'test/*'
            paths: {  }
        path_configs: {  }
    external_code_coverage:
        enabled: true
        timeout: 300
        runs: 1
        filter:
            excluded_paths:
                - 'spec/*'
                - 'test/*'
            paths: {  }
    php_mess_detector:
        enabled: true
        extensions:
            - php
        filter:
            excluded_paths:
                - 'spec/*'
                - 'test/*'
            paths: {  }
        config:
            ruleset: null
            code_size_rules:
                cyclomatic_complexity: false
                npath_complexity: false
                excessive_method_length: true
                excessive_class_length: false
                excessive_parameter_list: false
                excessive_public_count: false
                too_many_fields: false
                too_many_methods: false
                excessive_class_complexity: false
            design_rules:
                exit_expression: true
                eval_expression: true
                goto_statement: true
                number_of_class_children: false
                depth_of_inheritance: false
                coupling_between_objects: false
            unused_code_rules:
                unused_private_field: true
                unused_local_variable: true
                unused_private_method: true
                unused_formal_parameter: true
            naming_rules:
                constructor_conflict: true
                constant_naming: true
                boolean_method_name: false
            controversial_rules:
                superglobals: false
                camel_case_class_name: true
                camel_case_property_name: false
                camel_case_method_name: true
                camel_case_parameter_name: false
                camel_case_variable_name: false
        path_configs: {  }
    php_code_sniffer:
        enabled: true
        extensions:
            - php
        filter:
            excluded_paths:
                - 'spec/*'
                - 'test/*'
            paths: {  }
        config:
            tab_width: 0
            encoding: utf8
            standard: "PSR2"
        path_configs: {  }
    sensiolabs_security_checker:
        enabled: true
        filter:
            excluded_paths:
                - 'spec/*'
                - 'test/*'
            paths: {  }
    php_loc:
        enabled: true
        excluded_dirs:
            - vendor
            - test
            - spec
    php_cpd:
        enabled: true
        excluded_dirs:
            - vendor
            - test
            - spec
        names:
            - '*.php'
        min_lines: 5
        min_tokens: 70
        filter:
            excluded_paths:
                - 'spec/*'
                - 'test/*'
            paths: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'spec/*'
                - 'test/*'
            paths: {  }
filter:
    excluded_paths:
        - 'spec/*'
        - 'test/*'
        - 'vendor/*'
    paths: {  }

build_failure_conditions: {  }

application:
    type: none
