language: php

php:
  - 5.6
  - 5.5
  - 5.4

before_script:
  - composer self-update

install:
  - composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpspec run -v
  - vendor/bin/phpunit -c phpunit.xml.dist